version: "3.9"
services:
  delivery-bot-bot:
    container_name: delivery-bot-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /projects/delivery-bot/
    entrypoint: ["./docker/entry.sh", "bot"]
    networks:
      - delivery-bot-network
    depends_on:
      - delivery-bot-server
  delivery-bot-server:
    container_name: delivery-bot-server
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /projects/delivery-bot/
    entrypoint: ["./docker/entry.sh", "server"]
    networks:
      - delivery-bot-network

networks:
  delivery-bot-network:
    driver: bridge
    name: delivery-bot-network
